apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiserver
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: apiserver
        image: harish343/apigateway:1
        ports:
        - containerPort: 8000
        env:
        - name: MONGODB_DB_URL
          value: "mongodb://127.0.0.1:27017/users"
        - name: REDIS_DB_URL
          value: "127.0.0.1"
        - name: REDIS_DB_PORT
          value: "6379"
apiVersion: v1
kind: Service
metadata:
  name: apiservice
spec:
  type: NodePort
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30100