apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-deployment
  labels:
    app: order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order
        image: harish343/order:1
        ports:
        - containerPort: 2000
        env:
        - name: MONGODB_DB_URL
          value: "mongodb://127.0.0.1:27017/users"
        - name: REDIS_DB_URL
          value: "127.0.0.1"
        - name: REDIS_DB_PORT
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: orderservice
spec:
  
  selector:
    app: order
  ports:
    - protocol: TCP
      port: 2000
      targetPort: order
    

---
apiVersion: v1
kind: Endpoints
metadata:
  name: orderservice
subsets:
  - addresses:
    - ip: 127.0.0.1
    ports:
    - name: order
      port: 2000