apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-deployment
  labels:
    app: product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product
  template:
    metadata:
      labels:
        app: product
    spec:
      containers:
      - name: product
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 3000
        env:

        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: productservice
spec:
  
  selector:
    app: product
  ports:
    - protocol: TCP
      port: 3000
      targetPort: product
    

---
apiVersion: v1
kind: Endpoints
metadata:
  name: productservice
subsets:
  - addresses:
    - ip: 127.0.0.1
    ports:
    - name: product
      port: 3000