apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: nanajanashia/k8s-demo-app:v1.0
        ports:
        - containerPort: 4000
        env:

        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: mongo-config
              key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: userservice
spec:
  
  selector:
    app: user
  ports:
    - protocol: TCP
      port: 4000
      targetPort: user
    

---
apiVersion: v1
kind: Endpoints
metadata:
  name: userservice
subsets:
  - addresses:
    - ip: 127.0.0.1
    ports:
    - name: user
      port: 4000